api_platform:
    title: Bolatoki
    version: 1.0.0
    use_symfony_listeners: true
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: [ 'text/html' ]
    enable_format: false
    defaults:
        pagination_items_per_page: 100
        pagination_maximum_items_per_page: 1000
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        attributes:
            # normalization_context:
            #     groups: ['read']
            # denormalization_context:
            #     groups: ['write']