# nelmio_cors:
#     defaults:
#         allow_origin: ['https://bolatoki.bolatoki.eus', 'https://pruebas.bolatoki.eus']
#         allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': null